[project]
name = "neural-network-from-scratch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Nolan Augustine", email = "nolanaug@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.5.2",
]

[project.scripts]
neural-network-from-scratch = "neural_network_from_scratch:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.2",
]
